(test
 (name test_kernel)
 (libraries zenbu_kernel)
 (deps
  (glob_files fixtures/*.replay)))

(test
 (name test_model_runtime)
 (libraries zenbu_kernel zenbu_model_api zenbu_proof_models))

(test
 (name test_m3_models)
 (libraries zenbu_kernel zenbu_model_api zenbu_proof_models))

(test
 (name test_m4_terminal)
 (libraries zenbu_kernel zenbu_model_api zenbu_proof_models zenbu_view zenbu_terminal zenbu_app unix))
